export const USER_ACTION_TYPES = {
    SET_CURRENT_USER: 'USER_ACTION_TYPES_SET_CURRENT_USER',
    SET_CURRENT_USER_DOC: 'USER_ACTION_TYPES_SET_CURRENT_USER_DOC',
    LOGOUT_USER: 'USER_ACTION_TYPES_LOGOUT_USER'
}
