export const CATEGORIES_ACTION_TYPES = {
    FETCH_CATEGORIES_START: 'CATEGORIES_ACTION_TYPES_FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_SUCCESS: 'CATEGORIES_ACTION_TYPES_FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAILED: 'CATEGORIES_ACTION_TYPES_FETCH_CATEGORIES_FAILED',
}
