export const CARTS_ACTION_TYPES = {
    OPEN: 'CARTS_ACTION_TYPES_OPEN',
    CLOSE: 'CARTS_ACTION_TYPES_CLOSE',
    TOGGLE: 'CARTS_ACTION_TYPES_TOGGLE',
    RESET: 'CARTS_ACTION_TYPES_RESET',
    ADD_ITEM: 'CARTS_ACTION_TYPES_ADD_ITEM',
    DECREMENT_ITEM_QUANTITY: 'CARTS_ACTION_TYPES_DECREMENT_ITEM_QUANTITY',
    REMOVE_ITEM: 'CARTS_ACTION_TYPES_REMOVE_ITEM',
}
